version: '3.9'

services:
  db:
    image: postgres:13.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - '5432:5432'
  redis:
    image: redis:6.0
    restart: always
    ports:
      - '6379:6379'
