# Generated by Django 4.0.6 on 2022-07-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(verbose_name='Номер заказа')),
                ('dollar_price', models.IntegerField(verbose_name='Стоимость $')),
                ('order_date', models.DateField(verbose_name='Срок поставки')),
            ],
        ),
    ]
