# Generated by Django 4.0.6 on 2022-07-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(verbose_name='заказ №'),
        ),
    ]
